#ifndef _GOS_INCLUDE_BSP_YAML_
#define _GOS_INCLUDE_BSP_YAML_

#define GOS_BSP_esphome_name	growboard0

#include "bsp.h"

#include "bsps/common/esp32s2.yaml"
#include "bsps/common/bspAll.yaml"

#default GOS_CONFIG_CAMERA no
#default GOS_BSP_CONFIG_SHARE_PINS  false

#if GOS_CONFIG_CAMERA
#  redefine GOS_BSP_CONFIG_SHARE_PINS  true
#endif // GOS_CONFIG_CAMERA

#ifdef GOS_BSP_HAS_psram
psram:
  id: gosBsp_psram
  mode: octal
#if GOS_BSP_CONFIG_RUN_FAST
  speed: 80MHz
#else
  speed: 40MHz
#endif
#endif // GOS_BSP_HAS_psram

#ifdef GOS_BSP_HAS_spi
spi:
  id: gosBsp_spi
  clk_pin:
    number: GOS_BSP_PIN_TFT_SCLK
    allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
  mosi_pin:
    number: GOS_BSP_PIN_TFT_MOSI
    allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
  miso_pin:
    number: GOS_BSP_PIN_TFT_MISO
    allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
  interface: hardware
#endif // GOS_BSP_HAS_spi

#ifdef GOS_BSP_HAS_i2c
i2c:
  id: gosBsp_i2c
  sda:
    number: GOS_BSP_PIN_TWI_SDA
    allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
  scl:
    number: GOS_BSP_PIN_TWI_SCK
    allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
  frequency: 200kHz
  scan: true
#endif // GOS_BSP_HAS_i2c

#ifdef GOS_BSP_HAS_display
#ifdef GOS_BSP_HAS_backlight
output:
  - platform: gpio
    id: gosBsp_output_gpio_backlight
    pin:
      number: GOS_BSP_PIN_TFT_BACKLIGHT
      mode: output
    inverted: true

light:
  - platform: binary
    id: gosBsp_light_binary_backlight
    name: "Backlight Enable"
    output: gosBsp_output_gpio_backlight
#endif // GOS_BSP_HAS_backlight

#ifdef GOS_BSP_HAS_touchscreen
touchscreen:
  - platform: ft63x6
    id: gosBsp_touchscreen
    i2c_id: gosBsp_i2c
    display: gosBsp_display
    interrupt_pin: GOS_BSP_PIN_CTP_IRQ
    touch_timeout: 50ms
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: false
#if 0
    on_touch:
      - lambda: |-
           printf("touch: x=%d, y=%d, x_raw=%d, y_raw=%0d\n",
                    touch.x, touch.y, touch.x_raw, touch.y_raw);
#endif
#endif // GOS_BSP_HAS_touchscreen

display:
    platform: ili9xxx
    id: gosBsp_display
    model: ili9488_A
    spi_mode: mode3
    dimensions:
      width: 480
      height: 320
      offset_height: 0
      offset_width: 0
    color_order: bgr
    transform:
      mirror_y: false
      swap_xy: true
      mirror_x: false
    // rotation: 180
    invert_colors: false
    cs_pin:
      number: GOS_BSP_PIN_TFT_CS
      allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
    dc_pin:
      number: GOS_BSP_PIN_TFT_DC
      allow_other_uses: GOS_BSP_CONFIG_SHARE_PINS
    reset_pin: GOS_BSP_PIN_TFT_RST
    data_rate: 40MHz
#endif // GOS_BSP_HAS_display

#default GOS_BSP_CONFIG_PIN_TempData_output_led yes
#if GOS_BSP_CONFIG_PIN_TempData_output_led
output:
  - platform: slow_pwm
    id: gosBsp_output_slow_pwm_led
    pin:
      number: GOS_BSP_PIN_TempData
      mode: output
    period: 500ms

esphome:
  on_boot:
  - priority: 600
    then:
      - output.turn_on: gosBsp_output_slow_pwm_led
      - output.set_level:
          id: gosBsp_output_slow_pwm_led
          level: "90%"
#endif // GOS_BSP_CONFIG_PIN_TempData_output_led

#default GOS_BSP_CPU1_DEFAULTS_ON 0
switch:
  - platform: gpio
    id: switch_H_S_ENABLE
    name: "CPU1 Enable"
    pin:
      number: GOS_BSP_PIN_H_S_ENABLE
      mode: output
#if GOS_BSP_CPU1_DEFAULTS_ON
    restore_mode: ALWAYS_ON
#else
    restore_mode: ALWAYS_OFF
#endif // GOS_BSP_CPU1_DEFAULTS_ON

switch:
  - platform: gpio
    id: switch_TFT_PWR_EN
    name: "CPU0 Display Enable"
    pin:
      number: GOS_BSP_PIN_TFT_PWR_EN
      mode: output
    inverted: true
    restore_mode: ALWAYS_ON

#default GOS_CONFIG_BUZZER 0

#if GOS_CONFIG_BUZZER
output:
  - platform: ledc
    id: gosBsp_output_buzzer
    pin: GOS_BSP_PIN_BUZZER
    id: buzzer_out
    channel: 2 // xxx config item?

#default GOS_CONFIG_BUZZER_MONOTONE 0
#if GOS_CONFIG_BUZZER_MONOTONE
switch:
  - platform: output
    name: "CPU0 Buzzer"
    id: buzzer
    output: buzzer_out
    on_turn_on: 
      then:
        - delay: 0ms
        - output.turn_on: buzzer_out
        - output.ledc.set_frequency:
            id: buzzer_out
            frequency: "1000Hz"
        - output.set_level:
            id: buzzer_out
            level: "50%"
    on_turn_off:
      then:
        - delay: 0ms
        - output.turn_off: buzzer_out

#else // !GOS_CONFIG_BUZZER_MONOTONE

rtttl:
  output: buzzer_out

button:
  - platform: template
    name: "Buzzer play"
    on_press:
      then:
        - rtttl.play: 'mission_imp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'
  - platform: template
    name: "Buzzer stop"  
    on_press:
      then:
        - rtttl.stop

#endif // !GOS_CONFIG_BUZZER_MONOTONE
#endif // GOS_CONFIG_BUZZER

#default GOS_BSP_CONFIG_TINYUSB no
#if GOS_BSP_CONFIG_TINYUSB
esphome:
  includes:
    - GOS_HOME/utils/idfUsb.h
    - GOS_HOME/utils/idfUsb.c
  libraries:
    - "file://components/tinyusb"
    - "file://components/esp_tinyusb"
  platformio_options:
    build_flags:
      - -I components/tinyusb/src
      - -I components/esp_tinyusb/device/esp_tinyusb/include
      - -D CONFIG_TINYUSB_ENABLED=1       // tinyusb doesnt include sdkconfig.h
      - -D CONFIG_TINYUSB_CDC_ENABLED=1   // tinyusb doesnt include sdkconfig.h
      - -D CFG_TUSB_MCU=900               // for tinyusb tusb_option.h (ESP32S2)
      - -D CFG_TUSB_OS_INC_PATH=freertos/ // for tinyusb tusb_compiler.h

esp32:
  framework:
    components:
      - name: tinyusb
        source: "github://espressif/tinyusb@v0.14.3"
      - name: esp_tinyusb
        source: "github://espressif/esp-usb/device/esp_tinyusb"
    sdkconfig_options:
      CONFIG_TINYUSB: y
      CONFIG_TINYUSB_DESC_MANUFACTURER_STRING: "CyberGrow"
      CONFIG_TINYUSB_DESC_PRODUCT_STRING: "GrowBox v1.0"
      CONFIG_TINYUSB_DESC_CDC_STRING: "CyberGrow CDC Device"
      CONFIG_TINYUSB_CDC_ENABLED: y
      CONFIG_TINYUSB_CDC_COUNT: "2"
      CONFIG_TINYUSB_MSC_ENABLED: n
#endif

#default GOS_BSP_CONFIG_USB_ACM no
#if GOS_BSP_CONFIG_USB_ACM
esphome:
  on_boot:
  - priority: 80
    then:
      lambda: idfUsbInit();
#endif // GOS_BSP_CONFIG_USB_ACM

#default GOS_BSP_CONFIG_CONSOLE no
#if GOS_BSP_CONFIG_CONSOLE
esp32:
  partitions: GOS_BUILD_PATH/partitions.csv

esphome:
  platformio_options:
    // Enable FreeRTOS stats formatting functions, needed for 'tasks' command
    build_flags:
      - -D CONFIG_FREERTOS_USE_TRACE_FACILITY=1
      - -D CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
#endif // GOS_BSP_CONFIG_CONSOLE

#default GOS_BSP_CONFIG_CAMERA no

#if defined(GOS_BSP_CONFIG_CAMERA) && !defined(GOS_BSP_HAS_esp32_camera)
#  error BSP esp32_camera support is disabled.
#endif

#if GOS_BSP_CONFIG_CAMERA
esphome:
  libraries:
    - espressif/esp32-camera
  platformio_options:
    build_flags:
      - -D ESP_LWIP_COMPONENT_BUILD
      - -D CONFIG_SCCB_CLK_FREQ=100000
      - -I .piolibdeps/GOS_NAME/esp32-camera/target/jpeg_include

esp32:
  framework:
    sdkconfig_options:
      CONFIG_OV2640_SUPPORT: y
      CONFIG_SCCB_HARDWARE_I2C_PORT1: y
      CONFIG_SCCB_CLK_FREQ: "100000"
      CONFIG_CAMERA_TASK_STACK_SIZE: "2048"
      CONFIG_CAMERA_NO_AFFINITY: y
      CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX: "32768"
      # CONFIG_LCD_CAM_ISR_IRAM_SAFE: y
      // added for GOS_CONFIG_ESP32_CAMERA to build
      // CONFIG_IDF_TARGET_ESP32: "1"

switch:
  - platform: gpio
    id: gosBsp_switch_gpio_esp32_camera
    name: "CPU0 Camera Enable"
    pin:
      number: GOS_BSP_PIN_CSI_PWR_EN
      mode: output
    inverted: true
    restore_mode: ALWAYS_OFF

esp32_camera:
  // HW settings
  external_clock:
    pin:
      number: GOS_BSP_PIN_CSI_XCLK
      allow_other_uses: true
    frequency: 20MHz
  i2c_pins:
    sda:
      number: GOS_BSP_PIN_TWI_SDA
      allow_other_uses: true
    scl:
      number: GOS_BSP_PIN_TWI_SCK
      allow_other_uses: true
  data_pins:
    [
    {number: GOS_BSP_PIN_CSI_D2, allow_other_uses: true},
    {number: GOS_BSP_PIN_CSI_D3, allow_other_uses: true},
    GOS_BSP_PIN_CSI_D4,
    {number: GOS_BSP_PIN_CSI_D5, allow_other_uses: true},
    GOS_BSP_PIN_CSI_D6,
    GOS_BSP_PIN_CSI_D7,
    GOS_BSP_PIN_CSI_D8,
    GOS_BSP_PIN_CSI_D9
    ]
  vsync_pin: GOS_BSP_PIN_CSI_VSYNC
  href_pin:
    number: GOS_BSP_PIN_CSI_HREF
    allow_other_uses: true
  pixel_clock_pin: GOS_BSP_PIN_CSI_PCLK

  // Image settings
  name: MyCamera
  // ...
#endif // GOS_BSP_CONFIG_CAMERA

#ifdef GOS_BSP_HAS_uart
uart:
  id: uart_bus
  tx_pin: GOS_BSP_PIN_H_U0TXD
  rx_pin: GOS_BSP_PIN_H_U0RXD
  baud_rate: 115200
#endif // GOS_BSP_HAS_uart

#endif // _GOS_INCLUDE_BSP_YAML_
