#include "gos/gos.h"		// GrowOS header

#include GOS_STRINGIFY2(GOS_BSP_DIR,/bsp.yaml)	// GrowOS BSP header

#include "local.yaml"		// local defaults for any defaults

#include "gos/env.yaml"		// GrowOS build environment
#include "gos/gos.yaml"		// GrowOS system services
#include "gos/debug.yaml"	// GrowOS debug services
#include "gos/network.yaml"	// GrowOS network services

// now include the GrowOS application and GrowOS project yaml files.
// GOS_APP_PATH and GOS_PROJECT_DIR are relative to GOS_HOME  in order
// to pickup the generated versions that don't have hash-style comments.

#include GOS_STRINGIFY(GOS_APP_PATH)

#include GOS_STRINGIFY2(GOS_PROJECT_DIR,/project.yaml)

