esphome:
  name: t4-amoled
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
ota:
  password: !secret ota_password
wifi: !include wifi.yaml


external_components:
  - source: github://clydebarrow/esphome@cst226
    refresh: 10min
    components: [ cst226 ]
  - source: github://clydebarrow/esphome@amoled
    components: [ qspi_amoled ]
    refresh: always

spi:
  id: quad_spi
  clk_pin: 15
  data_pins:
    - 14
    - 10
    - 16
    - 12

i2c:
  sda: 6
  scl: 7

touchscreen:
  - platform: cst226
    id: my_touchscreen
    interrupt_pin: 8
    reset_pin: 17
    transform:
      mirror_x: true
      mirror_y: true

display:
  - platform: qspi_amoled
    model: RM690B0
    data_rate: 80MHz
    dimensions:
      width: 450
      height: 600
      offset_width: 16
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 11
    reset_pin: 13
    enable_pin: 9
    update_interval: never
    auto_clear_enabled: false

psram:
  mode: octal
  speed: 80MHz

packages:
  lvgl: !include lvgl-package.yaml

lvgl:
  full_refresh: true
  touchscreens:
    - touchscreen_id: my_touchscreen
      long_press_time: 800ms
      long_press_repeat_time: 400ms
  color_depth: 16
  byte_order: big_endian
