#if GOS_CONFIG_LVGL_BOOT_LOGO
image:
  - file: 'https://esphome.io/_images/logo.png'
    id: boot_logo
    resize: 200x200
    type: RGB565
#endif // GOS_CONFIG_LVGL_BOOT_LOGO

#define MY_FONT montserrat_18

lvgl:
  log_level: INFO
  displays:
    - display_id: gosBsp_display
  buffer_size: 50%
  touchscreens:
    - touchscreen_id: gosBsp_touchscreen
  default_font: MY_FONT
  disp_bg_color: 0x000000
  update_interval: 2s
#if GOS_CONFIG_LVGL_IDLE
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
#ifdef GOS_BSP_HAS_backlight
      - light.turn_off: light_TFT_BACKLIGHT
#endif
      - lvgl.pause:
#endif

#include "ui/lvglTheme.yaml"

#include "ui/lvglNavigation.yaml"
#if GOS_CONFIG_LVGL_BOOT_LOGO
#include "ui/lvglBootLogo.yaml"
#endif

  pages:
#include "ui/page1.yaml"
#include "ui/page2.yaml"
#include "ui/page3.yaml"
#include "ui/page4.yaml"

// Next are the page extras that are not part of the lvgl: definition

#include "ui/page1add.yaml"
#include "ui/page2add.yaml"
#include "ui/page3add.yaml"
#include "ui/page4add.yaml"
