#ifndef _GOS_INCLUDE_BSP_YAML_
#define _GOS_INCLUDE_BSP_YAML_

#include "pins.h"

#define GOS_APP				growBoardCpu0.yaml

#if GOS_USER_maarten
  #define GOS_SERIAL_NUM 100		// Maarten's growboard serial number
#elif GOS_USER_erik
  #define GOS_SERIAL_NUM 101		// Erik's growboard serial number
#endif

// advertise and setup hardware supported by this BSP

#define GOS_BSP_esp32_board		esp32-s2-kaluga-1
#define GOS_BSP_esp32_variant		esp32s2
#define GOS_BSP_esp32_flash_size	4MB

#define GOS_BSP_esphome_name		growboard
#define GOS_BSP_esphome_upload_speed	1500000
#define GOS_BSP_esphome_mcu		esp32s2
#define GOS_BSP_esphome_flash_size	GOS_BSP_esp32_flash_size

#ifdef GOS_CONFIG_RUN_FAST
    #define GOS_BSP_esphome_flash_mode	dout	    // or qio?
    #define GOS_BSP_esphome_f_flash	40000000L   // or 80Mhz?
    #define GOS_BSP_esphome_f_cpu	240000000L
#else
    #define GOS_BSP_esphome_flash_mode	dout
    #define GOS_BSP_esphome_f_flash	40000000L
    #define GOS_BSP_esphome_f_cpu	160000000L
#endif

#define GOS_BSP_HAS_psram
psram:
  id: gosBsp_psram
  mode: octal
  #if GOS_CONFIG_RUN_FAST
  speed: 80MHz
  #else
  speed: 40MHz
  #endif

#define GOS_BSP_HAS_spi
spi:
  id: gosBsp_spi
  clk_pin:
    number: _PIN_TFT_SCLK
#if GOS_CONFIG_CAMERA
    allow_other_uses: true
#endif // GOS_CONFIG_CAMERA
  mosi_pin:
    number: _PIN_TFT_MOSI
#if GOS_CONFIG_CAMERA
    allow_other_uses: true
#endif // GOS_CONFIG_CAMERA
  miso_pin:
    number: _PIN_TFT_MISO
#if GOS_CONFIG_CAMERA
    allow_other_uses: true
#endif // GOS_CONFIG_CAMERA
  interface: hardware

#define GOS_BSP_HAS_i2c
i2c:
  id: gosBsp_i2c
  sda:
    number: _PIN_TWI_SDA
#if GOS_CONFIG_CAMERA
    allow_other_uses: true
#endif
  scl:
    number: _PIN_TWI_SCK
#if GOS_CONFIG_CAMERA
    allow_other_uses: true
#endif
  frequency: 200kHz
  scan: true

#define GOS_BSP_HAS_backlight
#define GOS_BSP_BACKLIGHT_PIN _PIN_TFT_BACKLIGHT

#define GOS_BSP_HAS_touchscreen
#define GOS_BSP_NEEDS_ft63x6
touchscreen:
  - platform: ft63x6
    id: gosBsp_touchscreen
    i2c_id: gosBsp_i2c
    display: gosBsp_display
    interrupt_pin: _PIN_CTP_IRQ
    touch_timeout: 50ms
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: false
#if 0
    on_touch:
      - lambda: |-
           printf("touch: x=%d, y=%d, x_raw=%d, y_raw=%0d\n",
                    touch.x, touch.y, touch.x_raw, touch.y_raw);
#endif
#if GOS_CONFIG_LVGL && GOS_CONFIG_LVGL_IDLE
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
#ifdef GOS_BSP_HAS_backlight
            - light.turn_on: light_TFT_BACKLIGHT
#endif
#endif // GOS_CONFIG_LVGL && GOS_CONFIG_LVGL_IDLE

#define GOS_BSP_HAS_display
#define GOS_BSP_NEEDS_ili9xxx
display:
  - platform: ili9xxx
    id: gosBsp_display
    model: ili9488_A
    spi_mode: mode3
    dimensions:
      width: 480
      height: 320
      offset_height: 0
      offset_width: 0
#if GOS_CONFIG_DISPLAY_3_BIT
    color_palette: 3_BIT
#endif // GOS_CONFIG_DISPLAY_3_BIT
    color_order: bgr
    transform:
      mirror_y: false
      swap_xy: true
      mirror_x: false
    // rotation: 180
    invert_colors: false
    cs_pin:
      number: _PIN_TFT_CS
#if GOS_CONFIG_CAMERA
      allow_other_uses: true
#endif
    dc_pin:
      number: _PIN_TFT_DC
#if GOS_CONFIG_CAMERA
      allow_other_uses: true
#endif
    reset_pin: _PIN_TFT_RST
    data_rate: 40MHz
#if GOS_CONFIG_LVGL
    auto_clear_enabled: false
    update_interval: never
#else // !GOS_CONFIG_LVGL
    auto_clear_enabled: true
    update_interval: 1000ms
    // now define some pages using native esphome graphics
#include "nativeUi.yaml"
#endif // !GOS_CONFIG_LVGL

#endif // _GOS_INCLUDE_BSP_YAML_

