#ifdef GOS_BSP_HAS_backlight
#define GOS_BSP_NEEDS_light
#define GOS_BSP_NEEDS_output
#endif

#ifdef GOS_BSP_NEEDS_output

output:
#if GOS_CONFIG_APP0_LED
  - platform: slow_pwm
    pin:
      number: _PIN_TempData
      mode: output
    period: 500ms
    id: my_led
#endif // GOS_CONFIG_APP0_LED

#if GOS_CONFIG_BUZZER
  - platform: ledc
    pin: _PIN_BUZZER
    id: buzzer_out
    channel: 2 // xxx config item?
#endif // GOS_CONFIG_BUZZER

#ifdef GOS_BSP_HAS_backlight
  - platform: gpio
    id: output_TFT_BACKLIGHT
    pin:
      number: GOS_BSP_BACKLIGHT_PIN
      mode: output
    inverted: true
#endif // GOS_BSP_HAS_backlight

#endif // GOS_BSP_NEEDS_output

#ifdef GOS_BSP_NEEDS_light
light:

#ifdef GOS_BSP_HAS_backlight
  - platform: binary
    id: light_TFT_BACKLIGHT
    name: "Backlight Enable"
    output: output_TFT_BACKLIGHT
#endif // GOS_BSP_HAS_backlight

#endif // GOS_BSP_NEEDS_light

switch:
  - platform: restart
    name: "System Reboot"

  - platform: safe_mode
    name: "System Reboot (safe)"

  - platform: template
    name: "http request get"
    restore_mode: ALWAYS_OFF
    turn_on_action:
    - http_request.get:
        url: "http://127.0.0.1/sensor/net_wifi_signal_"
        on_response:
          then:
            - logger.log:
                format: "Response status: %d, duration_ms: %lu ms"
                args:
                  - response->status_code
                  - response->duration_ms

#if 00 && GOS_CONFIG_NET_TELNET_SERVER
  - platform: template
    name: "Net Telnet Server Init"
    turn_on_action:
      lambda: |-
        if (telnetServerInit() == ESP_FAIL)
            ESP_LOGD("telnetd", "Initializaton by switch failed");
        else
            ESP_LOGD("telnetd", "Initializaton succeeded");
#endif // GOS_CONFIG_NET_TELNET_SERVER

  - platform: gpio
    id: switch_H_S_ENABLE
    name: "CPU1 Enable"
    pin:
      number: _PIN_H_S_ENABLE
      mode: output
#if GOS_CONFIG_CPU1_DEFAULTS_ON
    restore_mode: ALWAYS_ON
#else
    restore_mode: ALWAYS_OFF
#endif // GOS_CONFIG_CPU1_DEFAULTS_ON

#if GOS_CONFIG_DISPLAY
  - platform: gpio
    id: switch_TFT_PWR_EN
    name: "CPU0 Display Enable"
    pin:
      number: _PIN_TFT_PWR_EN
      mode: output
    inverted: true
#if GOS_CONFIG_TFT_PWR_DEFAULTS_ON
    restore_mode: ALWAYS_ON
#else
    restore_mode: ALWAYS_OFF
#endif // GOS_CONFIG_TFT_PWR_DEFAULTS_ON

#endif // GOS_CONFIG_DISPLAY

#if GOS_CONFIG_CAMERA
  - platform: gpio
    id: switch_CAMERA
    name: "CPU0 Camera Enable"
    pin:
      number: _PIN_CSI_PWR_EN
      mode: output
    inverted: true
#if GOS_CONFIG_CAMERA_DEFAULTS_ON
    restore_mode: ALWAYS_ON
#else
    restore_mode: ALWAYS_OFF
#endif // GOS_CONFIG_CAMERA_DEFAULTS_ON
#endif // GOS_CONFIG_CAMERA
#
#if GOS_CONFIG_BUZZER
#if GOS_CONFIG_BUZZER_MONOTONE
  - platform: output
    name: "CPU0 Buzzer"
    id: buzzer
    output: buzzer_out
    on_turn_on: 
      then:
        - delay: 0ms
        - output.turn_on: buzzer_out
        - output.ledc.set_frequency:
            id: buzzer_out
            frequency: "1000Hz"
        - output.set_level:
            id: buzzer_out
            level: "50%"
    on_turn_off:
      then:
        - delay: 0ms
        - output.turn_off: buzzer_out

#else // !GOS_CONFIG_BUZZER_MONOTONE

rtttl:
  output: buzzer_out

button:
  - platform: template
    name: "Buzzer play"
    on_press:
      then:
        - rtttl.play: 'mission_imp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'
  - platform: template
    name: "Buzzer stop"  
    on_press:
      then:
        - rtttl.stop

#endif // !GOS_CONFIG_BUZZER_MONOTONE
#endif // GOS_CONFIG_BUZZER

#if GOS_CONFIG_LVGL && GOS_CONFIG_LVGL_IDLE && GOS_CONFIG_LVGL_ANTIBURN
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:
#endif // GOS_DISPLAY_LVGL && GOS_CONFIG_LVGL_IDLE && GOS_CONFIG_LVGL_ANTIBURN


#if GOS_CONFIG_CAMERA
esp32_camera:
  // HW settings
  external_clock:
    pin:
      number: _PIN_CSI_XCLK
      allow_other_uses: true
    frequency: 20MHz
  i2c_pins:
    sda:
      number: _PIN_TWI_SDA
      allow_other_uses: true
    scl:
      number: _PIN_TWI_SCK
      allow_other_uses: true
  data_pins:
    [
    {number: _PIN_CSI_D2, allow_other_uses: true},
    {number: _PIN_CSI_D3, allow_other_uses: true},
    _PIN_CSI_D4,
    {number: _PIN_CSI_D5, allow_other_uses: true},
    _PIN_CSI_D6,
    _PIN_CSI_D7,
    _PIN_CSI_D8,
    _PIN_CSI_D9
    ]
  vsync_pin: _PIN_CSI_VSYNC
  href_pin:
    number: _PIN_CSI_HREF
    allow_other_uses: true
  pixel_clock_pin: _PIN_CSI_PCLK

  // Image settings
  name: My Camera
  // ...
#endif // GOS_CONFIG_CAMERA

