substitutions:
  PIN_H_GPIO0: GPIO0
  PIN_CSI_VSYNC: GPIO1
  PIN_CSI_D9: GPIO2
  PIN_CSI_D8: GPIO3
  PIN_CSI_D7: GPIO4
  PIN_CSI_D6: GPIO5
  PIN_CTP_IRQ: GPIO6
  PIN_CTP_RST: GPIO7
  PIN_TFT_RST: GPIO7
  PIN_TWI_SDA: GPIO8
  PIN_TWI_SCK: GPIO9
  PIN_CSI_PWR_EN: GPIO10
  PIN_CSI_PCLK: GPIO11
  PIN_CSI_D4: GPIO12
  PIN_H_S_ENABLE: GPIO13
  PIN_PWROFF_INT: GPIO14
  PIN_XCTL_HIGH: GPIO15
  PIN_XCTL_LOW: GPIO16
  PIN_TempData: GPIO17
  PIN_TFT_PWR_EN: GPIO18
  PIN_H_USB_NEG: GPIO19
  PIN_H_USB_POS: GPIO20
  PIN_TFT_BACKLIGHT: GPIO21
  PIN_MYSTERY: GPIO26
  PIN_TFT_CS: GPIO33
  PIN_CSI_HREF: GPIO33
  PIN_TFT_DC: GPIO34
  PIN_CSI_XCLK: GPIO34
  PIN_TFT_MOSI: GPIO35
  PIN_CSI_D2: GPIO35
  PIN_TFT_SCLK: GPIO36
  PIN_CSI_D3: GPIO36
  PIN_TFT_MISO: GPIO37
  PIN_CSI_D5: GPIO37
  PIN_VBAT_SENSE: GPIO38
  PIN_H_GPIO39: GPIO39
  PIN_H_GPIO40: GPIO40
  PIN_H_GPIO41: GPIO41
  PIN_H_GPIO42: GPIO42
  PIN_BUZZER: GPIO42
  PIN_H_U0TXD: GPIO43
  PIN_H_U0RXD: GPIO44
  PIN_VBAT_CE: GPIO45
