
switch:
  - platform: gpio
    pin: _PIN_SET_MOTOR_MINUS
    name: "12V Motor minus"
    id: motorMinus
    interlock: &motor12Vinterlock [motorMinus, motorPlus]
    interlock_wait_time: 500ms

  - platform: gpio
    pin: _PIN_SET_MOTOR_PLUS
    name: "12V Motor plus"
    id: motorPlus
    interlock: *motor12Vinterlock
    interlock_wait_time: 500ms

  - platform: gpio
    pin: _PIN_DLOCK_GND_EN
    name: "12V Door Lock Enable"
    id: actDoorLockEnable

  - platform: gpio
    pin: _PIN_ACT_AIR
    name: "12V Air pump"
    id: actAirPump

  - platform: gpio
    pin: _PIN_ACT_12V
    name: "12V Small Fan"
    id: actSmallFan

  - platform: gpio
    pin: _PIN_ACT_LED
    name: "AC Led Panel"
    id: actLedPanel

  - platform: gpio
    pin: _PIN_ACT_PUMP
    name: "AC Water Pump"
    id: actWaterPump

  - platform: gpio
    pin: _PIN_ACT_AUX
    name: "AC Aux Heater"
    id: actAuxHeater

