#include "config.h"
#include "cpu.h"
#include "env.cpr"
#include "sensor.cpr"
#include "network.cpr"

#if _CPU == 0
  #if GB_CONFIG_DISPLAY
    #include "display.cpr"
    #include "images.cpr"
    #include "menu.cpr"
  #endif // GB_CONFIG_DISPLAY
  #include "app0.cpr"
#else // _CPU == 1
  #include "app1.cpr"
#endif // _CPU == 1
