substitutions:
  <<: !include pinsCpu0.yaml

<<: !include env.yaml

# flash the led using a slow software-based PWM
# esphome.on_boot:
#  priority: -100
#  then:
#    - output.turn_on:
#        my_slow_pwm  
#    - output.set_level:
#        id: my_slow_pwm
#        level: "90%"
#
light:
  - platform: status_led
    id: cpu0_status_led
    name: "Status LED"
    pin: $PIN_TempData
    effects:
      - strobe:
          name: blink_slow
          colors:
            - state: true
              duration: 1s
            - state: false
              duration: 1s

output:
  - platform: ledc
    pin: $PIN_BUZZER
    id: buzzer_output

#  - platform: slow_pwm
#    pin: $PIN_TempData
#    id: my_slow_pwm
#    period: 500ms
#    restart_cycle_on_state_change: true

switch:
  - platform: gpio
    id: switch_H_S_ENABLE
    name: "Secondary CPU Enable"
    pin:
      number: $PIN_H_S_ENABLE
      mode: output
    restore_mode: ALWAYS_ON

  - platform: gpio
    id: switch_TFT_PWR_EN
    name: "Display Enable"
    pin:
      number: $PIN_TFT_PWR_EN
      mode: output
    inverted: true
    restore_mode: ALWAYS_ON

  - platform: gpio
    id: switch_TFT_BACKLIGHT
    name: "Display Backlight"
    pin:
      number: $PIN_TFT_BACKLIGHT
      mode: output
    inverted: true
    # To save power and not burn screen, the backlight defaults off.
    # It can be turned on from the web server.
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: "Reboot"

#  - platform: gpio
#    pin:
#      number: $PIN_TempData
#      mode: output
#    id: led

  - platform: output
    name: "Buzzer"
    id: buzzer
    output: buzzer_output
    on_turn_on: 
      then:
        - output.turn_on: buzzer_output
        - output.ledc.set_frequency:
            id: buzzer_output
            frequency: "1000Hz"
        - output.set_level:
            id: buzzer_output
            level: "50%"

    on_turn_off:
      then:
        - output.turn_off: buzzer_output

#interval:
#  - interval: 500ms
#    then:
#      - switch.toggle: led
      # - logger.log: "LED toggling"

# on_turn_on:
#     - rtttl.play: 'MissionImp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'
#     on_turn_off:
#     - rtttl.stop

<<: !include display.yaml

# Enable logging
logger:
  # level: DEBUG
  logs:
    component: ERROR

<<: !include network.yaml
