#ifndef _INCLUDE_CPU0_H_
#define _INCLUDE_CPU0_H_

#define _PIN_H_GPIO0	GPIO0
#define _PIN_CSI_VSYNC	GPIO1
#define _PIN_CSI_D9	GPIO2
#define _PIN_CSI_D8	GPIO3
#define _PIN_CSI_D7	GPIO4
#define _PIN_CSI_D6	GPIO5
#define _PIN_CTP_IRQ	GPIO6
#define _PIN_CTP_RST	GPIO7
#define _PIN_TFT_RST	GPIO7
#define _PIN_TWI_SDA	GPIO8
#define _PIN_TWI_SCK	GPIO9
#define _PIN_CSI_PWR_EN	GPIO10
#define _PIN_CSI_PCLK	GPIO11
#define _PIN_CSI_D4	GPIO12
#define _PIN_H_S_ENABLE	GPIO13
#define _PIN_PWROFF_INT	GPIO14
#define _PIN_XCTL_HIGH	GPIO15
#define _PIN_XCTL_LOW	GPIO16
#define _PIN_TempData	GPIO17
#define _PIN_TFT_PWR_EN	GPIO18
#define _PIN_H_USB_NEG	GPIO19
#define _PIN_H_USB_POS	GPIO20
#define _PIN_TFT_BACKLIGHT GPIO21
#define _PIN_MYSTERY	GPIO26
#define _PIN_TFT_CS	GPIO33
#define _PIN_CSI_HREF	GPIO33
#define _PIN_TFT_DC	GPIO34
#define _PIN_CSI_XCLK	GPIO34
#define _PIN_TFT_MOSI	GPIO35
#define _PIN_CSI_D2	GPIO35
#define _PIN_TFT_SCLK	GPIO36
#define _PIN_CSI_D3	GPIO36
#define _PIN_TFT_MISO	GPIO37
#define _PIN_CSI_D5	GPIO37
#define _PIN_VBAT_SENSE	GPIO38
#define _PIN_H_GPIO39	GPIO39
#define _PIN_H_GPIO40	GPIO40
#define _PIN_H_GPIO41	GPIO41
#define _PIN_H_GPIO42	GPIO42
#define _PIN_BUZZER	GPIO42
#define _PIN_H_U0TXD	GPIO43
#define _PIN_H_U0RXD	GPIO44
#define _PIN_VBAT_CE	GPIO45

#endif // _INCLUDE_CPU0_H_
