// Enable logging
logger:
#if _USER_maarten
  hardware_uart: USB_CDC
  deassert_rts_dtr: true
  baud_rate: 921600
#else
  # baud_rate: 115200
  baud_rate: 921600
  hardware_uart: UART0
#endif
    # level: ERROR
  level: DEBUG
    # level: VERBOSE
  logs:
    # ili9xxx.component: VERBOSE
    component: DEBUG
    # component: VERBOSE

#if GB_CONFIG_DEBUG
debug:
  update_interval: 15s

#endif // GB_CONFIG_DEBUG
