// Enable logging
logger:
#if _USER_maarten
#if _CPU==0
  hardware_uart: USB_CDC
  // deassert_rts_dtr: true
  //baud_rate: 921600
#else
  hardware_uart: USB_CDC
  // XXX setup secondary in env.yaml
  // hardware_uart: UART0
  // baud_rate: 115200
#endif
#else
  # baud_rate: 115200
  baud_rate: 921600
  hardware_uart: UART0
#endif
    # level: ERROR
  level: DEBUG
    # level: VERBOSE
  logs:
    # ili9xxx.component: VERBOSE
    component: DEBUG
    # component: VERBOSE

#if GOS_CONFIG_DEBUG
debug:
  update_interval: 15s
#endif // GOS_CONFIG_DEBUG

#if GOS_CONFIG_SERIAL_SERVER
uart:
  id: uart_bus
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 115200 

stream_server:
  uart_id: uart_bus
  port: 1234

binary_sensor: // should be in sensor.yaml
  - platform: stream_server
    connected:
      name: Connected

#if 0	// would have to move this to sensor.yaml
sensor:
  - platform: stream_server
    connection_count:
      name: Number of connections
#endif
#endif // GOS_CONFIG_SERIAL_SERVER

