#if !GB_CONFIG_LVGL
#include "nativeUiInit.yaml"
#endif // !GB_CONFIG_LVGL

spi:
  clk_pin:
    number: _PIN_TFT_SCLK
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  mosi_pin:
    number: _PIN_TFT_MOSI
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  miso_pin:
    number: _PIN_TFT_MISO
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  interface: hardware

// for 3-bit or lvgl displays we need external components
#if GB_CONFIG_DISPLAY_3_BIT || GB_CONFIG_LVGL || GB_CONFIG_SERIAL_SERVER
external_components:
#if GB_CONFIG_DISPLAY_3_BIT
// added 3-bit mode to the display driver
#if _USER_maarten
  - source:
      type: local
      path: ~/git/esphome_components/components
#else
  - source: 'github://maartenSXM/esphome_components'
#endif
    components: [ ili9xxx ]
#endif // GB_CONFIG_DISPLAY_3_BIT
#if GB_CONFIG_LVGL
  - source: 'github://pr#6363'
    refresh: 1000min
    components: [lvgl]
#endif // GB_CONFIG_LVGL

#if GB_CONFIG_SERIAL_SERVER
  - source: 'github://oxan/esphome-stream-server'
    refresh: 1000min
    components: [stream_server]
#endif // GB_CONFIG_SERIAL_SERVER

#endif // GB_CONFIG_DISPLAY_3_BIT || GB_CONFIG_LVGL || GB_CONFIG_SERIAL_SERVER

display:
  - platform: ili9xxx
    model: ili9488_A
    spi_mode: mode3
    id: my_display
    dimensions:
      width: 480
      height: 320
      offset_height: 0
      offset_width: 0
#if GB_CONFIG_DISPLAY_3_BIT
    color_palette: 3_BIT
#endif // GB_CONFIG_DISPLAY_3_BIT
    color_order: bgr
    transform:
      mirror_y: false
      swap_xy: true
      mirror_x: false
    // rotation: 180
    invert_colors: false
    cs_pin:
      number: _PIN_TFT_CS
#if GB_CONFIG_CAMERA
      allow_other_uses: true
#endif
    dc_pin:
      number: _PIN_TFT_DC
#if GB_CONFIG_CAMERA
      allow_other_uses: true
#endif
    reset_pin: _PIN_TFT_RST
    data_rate: 40MHz
#if GB_CONFIG_LVGL
    auto_clear_enabled: false
    update_interval: never
#else // !GB_CONFIG_LVGL
    auto_clear_enabled: true
    update_interval: 1000ms
    // now define some pages using native esphome graphics
#include "nativeUi.yaml"
#endif // !GB_CONFIG_LVGL

i2c:
  id: i2cBusIntern
  sda: 
    number: _PIN_TWI_SDA
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif
  scl:
    number: _PIN_TWI_SCK
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif
  frequency: 200kHz
  scan: true

touchscreen:
 - platform: ft63x6
   id: my_touchScreen
   i2c_id: i2cBusIntern
   display: my_display
   interrupt_pin: _PIN_CTP_IRQ
   touch_timeout: 50ms
   transform:
     swap_xy: true
     mirror_x: true
     mirror_y: false
#if 0
   on_touch:
     - lambda: |-
           printf("touch: x=%d, y=%d, x_raw=%d, y_raw=%0d\n",
                    touch.x, touch.y, touch.x_raw, touch.y_raw);
#endif
#if GB_CONFIG_LVGL && GB_CONFIG_LVGL_IDLE
   on_release:
     - if:
         condition: lvgl.is_paused
         then:
           - logger.log: "LVGL resuming"
           - lvgl.resume:
           - lvgl.widget.redraw:
           - light.turn_on: light_TFT_BACKLIGHT
#endif // GB_CONFIG_LVGL && GB_CONFIG_LVGL_IDLE
