spi:
  clk_pin:
    number: _PIN_TFT_SCLK
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  mosi_pin:
    number: _PIN_TFT_MOSI
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  miso_pin:
    number: _PIN_TFT_MISO
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif // GB_CONFIG_CAMERA
  interface: hardware

color:
  - id: my_black
    hex: '000000'
  - id: my_red
    hex: 'FF0000'
  - id: my_green
    hex: '00FF00'
  - id: my_yellow
    hex: 'FFFF00'
  - id: my_blue
    hex: '0000FF'
  - id: my_magenta
    hex: 'FF00FF'
  - id: my_cyan
    hex: '00FFFF'
  - id: my_white
    hex: 'FFFFFF'

font:
  - file: 'fonts/arial.ttf'
    id: arial
    size: 24

// added 3-bit mode to the display driver
external_components:
#if _USER_maarten
  - source:
      type: local
      path: ~/git/esphome_components/components
#else
  - source: 'github://maartenwrs/esphome_components'
#endif
    components: [ ili9xxx ]

globals:
  - id: touchx
    type: unsigned int
    restore_value: no
    initial_value: '0'
  - id: touchy
    type: unsigned int
    restore_value: no
    initial_value: '0'
  - id: my_init_flag
    type: unsigned int
    restore_value: no
    initial_value: '0'
  - id: sntpBootTime
    type: time_t
    restore_value: no
    initial_value: '0'

display:
  - platform: ili9xxx
    model: ili9488_A
    spi_mode: mode3
    id: my_display
    dimensions:
      width: 480
      height: 320
      offset_height: 0
      offset_width: 0
    color_palette: 3_BIT
    color_order: bgr
    transform:
      mirror_y: false
      swap_xy: true
      mirror_x: false
    // rotation: 180
    invert_colors: false
    auto_clear_enabled: true
    cs_pin:
      number: _PIN_TFT_CS
#if GB_CONFIG_CAMERA
      allow_other_uses: true
#endif
    dc_pin:
      number: _PIN_TFT_DC
#if GB_CONFIG_CAMERA
      allow_other_uses: true
#endif
    reset_pin: _PIN_TFT_RST
    data_rate: 40MHz
    update_interval: 500ms
    pages:
    - id: page1
      lambda: |-
        it.print(440, 0, id(arial), id(my_cyan), TextAlign::TOP_RIGHT, "Page 1");
        // it.image(0,0,id(image_beansprouts));
        it.filled_circle(140, 120, 20, id(my_red));
        it.filled_circle(200, 120, 20, id(my_green));
        it.filled_circle(260, 120, 20, id(my_yellow));
        it.filled_circle(320, 120, 20, id(my_blue));
        it.filled_circle(380, 120, 20, id(my_magenta));
        it.filled_circle(440, 120, 20, id(my_cyan));
        it.filled_circle(240, 160, 20, id(my_white));
        it.filled_circle(240, 160, 10, id(my_black));

        it.line(100, 60, 200, 70, id(my_black));
        it.line(100, 62, 200, 72, id(my_red));
        it.line(100, 64, 200, 74, id(my_green));
        it.line(100, 66, 200, 76, id(my_yellow));
        it.line(100, 68, 200, 78, id(my_blue));
        it.line(100, 70, 200, 80, id(my_magenta));
        it.line(100, 72, 200, 82, id(my_cyan));
        it.line(100, 74, 200, 84, id(my_white));

        it.image(  0,320-75,id(icon_left));
        it.image( 80,320-75,id(icon_right));
        it.image(160,320-75,id(icon_up));
        it.image(240,320-75,id(icon_down));
        it.image(320,320-75,id(icon_select));
        it.image(400,320-75,id(icon_cancel));
        // it.image(0,0,id(image_beansprouts));
        // menu gets half the display width & height
        it.menu(0, 0, id(my_menu), 240, 160);

    - id: page2
      lambda: |-
        it.print(440, 0, id(arial), id(my_magenta), TextAlign::TOP_RIGHT, "Page 2");
        it.image(  0,320-75,id(icon_left));
        it.image( 80,320-75,id(icon_right));
        it.image(160,320-75,id(icon_up));
        it.image(240,320-75,id(icon_down));
        it.image(320,320-75,id(icon_select));
        it.image(400,320-75,id(icon_cancel));

    //  it.menu(0,0,id(my_menu),0,240);
    //  it.line(0, 0, 100, 50);
    // #include "tests/displayBlocks.yaml"
    // #include "tests/displayCircles.yaml"

i2c:
  id: i2cBusIntern
  sda: 
    number: _PIN_TWI_SDA
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif
  scl:
    number: _PIN_TWI_SCK
#if GB_CONFIG_CAMERA
    allow_other_uses: true
#endif
  frequency: 400kHz
  scan: false

touchscreen:
 - platform: ft63x6
   id: my_touchScreen
   i2c_id: i2cBusIntern
   interrupt_pin: _PIN_CTP_IRQ
   transform:
     swap_xy: true
     mirror_x: true
#if 1
   on_touch:
     lambda: |-
       id(touchx) = touch.x;
       id(touchy) = touch.y;
       #  printf("x=%d, y=%d\n", touch.x, touch.y);
       printf("x=%d, y=%d\n", id(touchx), id(touchy));
#endif

