globals:
  - id: my_init_flag
    type: unsigned int
    restore_value: no
    initial_value: "0"
  #ifdef GOS_PROJTAG_0
  #if GOS_CONFIG_DISPLAY
  - id: touchx
    type: unsigned int
    restore_value: no
    initial_value: "0"
  - id: touchy
    type: unsigned int
    restore_value: no
    initial_value: "0"
  #endif // GOS_CONFIG_DISPLAY
  #endif // GOS_PROJTAG_0
  #if GOS_CONFIG_NET_SNTP
  - id: sntpBootTime
    type: time_t
    restore_value: no
    initial_value: "0"
#endif // GOS_CONFIG_NET_SNTP

