globals:
  - id: my_init_flag
    type: unsigned int
    restore_value: no
    initial_value: "0"
  #if _CPU == 0 && GB_CONFIG_DISPLAY
  - id: touchx
    type: unsigned int
    restore_value: no
    initial_value: "0"
  - id: touchy
    type: unsigned int
    restore_value: no
    initial_value: "0"
  #endif // GB_CONFIG_DISPLAY
  #if GB_CONFIG_NET_SNTP
  - id: sntpBootTime
    type: time_t
    restore_value: no
    initial_value: "0"
#endif // GB_CONFIG_NET_SNTP

