#  yaml style comments are allowed
// C-style comments are allowed
/* traditional C-ctyle comments are too */

#include "gos.h"

#include "env.yaml"
#include "globals.yaml"
#include "numbers.yaml"
#include "debug.yaml"
#include "sensor.yaml"
#include "network.yaml"

#ifdef GOS_PROJTAG_0
# if GOS_CONFIG_DISPLAY
#  include "display.yaml"
#  if GOS_CONFIG_LVGL
#   include "ui/lvglMain.yaml"
#  endif // GOS_CONFIG_LVGL
# endif // GOS_CONFIG_DISPLAY
# include "app0.yaml"
#else // ! GOS_PROJTAG_0
# include "app1.yaml"
#endif // ! GOS_PROJTAG_0
