# Enable Home Assistant API
#api:
#   password: ""

ota:
  password: ""

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret wifi_addr
    gateway: !secret wifi_gateway
    subnet: !secret wifi_netmask
    dns1: !secret wifi_gateway
  fast_connect: on

# Enable fallback hotspot (captive portal) in case wifi connection fails
# ap:
#   ssid: "Gbcpu0 Fallback Hotspot"
#   password: "2MVT9gyfV0D4"

captive_portal:
    
time:
  - platform: sntp
    id: sntpTime
    timezone: !secret ntp_timezone
    servers:
      - !secret ntp_server
    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"

          # lambda: |-
          # id(sntpBootTime) = id(sntpTime);

text_sensor:
  - platform: template
    name: "Net SNTP Time"
    update_interval: 30s
    lambda: |-
      auto time_text = (std::string) "Unknown";
      if (id(sntpTime).now().is_valid())
        time_text = id(sntpTime).now().strftime("%d/%m/%Y %H:%M:%S");
      return time_text;

  - platform: template
    id: sntpBootTimeText
    name: "System Boot Time"
    # update_interval: never
    lambda: |-
      static char str[25];
      static time_t bootTime;

      if (bootTime == (time_t) 0)
        {
        if (!id(sntpTime).now().is_valid())
          return ((std::string) "Unknown");
        bootTime = id(sntpTime).now().timestamp;
        strftime(str, sizeof(str), "%d/%m/%Y %H:%M:%S", localtime(&bootTime));
        }
      return (std::string) str;

  - platform: wifi_info
    ip_address:
      name: Net IP Address
    ssid:
      name: Net WiFi SSID
    mac_address:
      name: Net MAC Address
