# Enable Home Assistant API
#api:
#   password: ""

ota:
  password: ""

web_server:

wifi:
  ssid: $sub_wifi_ssid
  password: $sub_wifi_password
  manual_ip:
    static_ip: $sub_wifi_addr_$CPU
    gateway: $sub_wifi_gateway
    subnet: $sub_wifi_netmask
    dns1: $sub_wifi_gateway
  fast_connect: on

# Enable fallback hotspot (captive portal) in case wifi connection fails
# ap:
#   ssid: gbCpu$CPU Hotspot
#   password: $sub_wifi_password

captive_portal:
    
time:
  - platform: sntp
    id: sntpTime
    timezone: $sub_ntp_timezone
    servers:
      - $sub_ntp_server
    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"

          # lambda: |-
          # id(sntpBootTime) = id(sntpTime);

