#if (GB_CONFIG_INTERNAL_TEMP || GB_CONFIG_NET_WIFI || GB_CONFIG_DEBUG)
sensor:
#if GB_CONFIG_INTERNAL_TEMP
  - platform: internal_temperature
    name: "System Temperature"
    update_interval: 15s
#endif // GB_CONFIG_INTERNAL_TEMP

#if GB_CONFIG_NET_WIFI
  - platform: wifi_signal
    id: my_wifi_sensor
    name: "Net WiFi Signal "
    update_interval: 15s
#endif // GB_CONFIG_NET_WIFI

#if GB_CONFIG_DEBUG
  - platform: uptime
    name: System Uptime 
    update_interval: 15s

  - platform: debug
    free:
      name: "System Heap Free"
    block:
      name: "System Heap Max Block"
    loop_time:
      name: "System Loop Time"
    psram:
      name: "System Free PSRAM"

#endif // GB_CONFIG_DEBUG
#endif // (GB_CONFIG_INTERNAL_TEMP || GB_CONFIG_NET_WIFI || GB_CONFIG_DEBUG)

text_sensor:
#if GB_CONFIG_NET_WIFI
#if GB_CONFIG_NET_SNTP
  - platform: template
    name: "Net SNTP Time"
    update_interval: 30s
    lambda: |-
      auto time_text = (std::string) "Unknown";
      if (id(sntpTime).now().is_valid())
        time_text = id(sntpTime).now().strftime("%d/%m/%Y %H:%M:%S");
      return time_text;

  - platform: template
    id: sntpBootTimeText
    name: "System Boot Time"
    // update_interval: never
    lambda: |-
      static char str[25];

      if (id(sntpBootTime) == (time_t) 0)
          return ((std::string) "Unknown");
      if (str[0] == '\0')
        strftime(str, sizeof(str), "%d/%m/%Y %H:%M:%S", localtime(&id(sntpBootTime)));
      return (std::string) str;
#endif // GB_CONFIG_NET_SNTP
#endif // GB_CONFIG_NET_WIFI

#if GB_CONFIG_NET_WIFI
  - platform: wifi_info
    ip_address:
      name: Net IP Address
    ssid:
      name: Net WiFi SSID
    mac_address:
      name: Net MAC Address
#endif // GB_CONFIG_NET_WIFI

  - platform: debug
    // device:
    //   name: "System Info"
    reset_reason:
      name: "System Reset Reason"

