#if (GOS_CONFIG_INTERNAL_TEMP || GOS_CONFIG_NET_WIFI || GOS_CONFIG_DEBUG)
sensor:
  #if GOS_CONFIG_INTERNAL_TEMP
  - platform: internal_temperature
    name: "System Temperature"
    update_interval: 5s
    #if GOS_CONFIG_LVGL
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]
    #endif // GOS_CONFIG_LVGL
  #endif // GOS_CONFIG_INTERNAL_TEMP

  #if GOS_CONFIG_NET_WIFI
  - platform: wifi_signal
    id: my_wifi_sensor
    name: "Net WiFi Signal "
    update_interval: 15s

  #endif // GOS_CONFIG_NET_WIFI

  #if GOS_CONFIG_DEBUG
  - platform: uptime
    name: System Uptime
    update_interval: 15s

  - platform: debug
    free:
      name: "System Heap Free"
    block:
      name: "System Heap Max Block"
    loop_time:
      name: "System Loop Time"
    psram:
      name: "System Free PSRAM"

#endif // GOS_CONFIG_DEBUG
#endif // (GOS_CONFIG_INTERNAL_TEMP || GOS_CONFIG_NET_WIFI || GOS_CONFIG_DEBUG)

text_sensor:
  #if GOS_CONFIG_NET_WIFI
  #if GOS_CONFIG_NET_SNTP
  - platform: template
    name: "Net SNTP Time"
    update_interval: 30s
    lambda: |-
      auto time_text = (std::string) "Unknown";
      if (id(sntpTime).now().is_valid())
        time_text = id(sntpTime).now().strftime("%d/%m/%Y %H:%M:%S");
      return time_text;

  - platform: template
    id: sntpBootTimeText
    name: "System Boot Time"
    // update_interval: never
    lambda: |-
      static char str[25];

      if (id(sntpBootTime) == (time_t) 0)
          return ((std::string) "Unknown");
      if (str[0] == '\0')
        strftime(str, sizeof(str), "%d/%m/%Y %H:%M:%S", localtime(&id(sntpBootTime)));
      return (std::string) str;

  - platform: template
    id: wifi_channel
    name: "Net WiFi Channel"
    lambda: |-
      static char str[3]; // one or two digits (or -1) plus NULL
      sprintf(str, "%2d", idfWifiGetChannelNum());
      return (std::string) str;
  
  #endif // GOS_CONFIG_NET_SNTP
  #endif // GOS_CONFIG_NET_WIFI

  #if GOS_CONFIG_NET_WIFI
  - platform: wifi_info
    ip_address:
      id: wifi_ip_address
      name: "Net IP Address"
    ssid:
      id: wifi_ip_ssid
      name: "Net WiFi SSID"
    mac_address:
      id: wifi_ip_mac
      name: "Net MAC Address"

  #endif // GOS_CONFIG_NET_WIFI

#if GOS_CONFIG_DEBUG
  - platform: debug
    // device:
    //   name: "System Info"
    reset_reason:
      name: "System Reset Reason"
#endif // GOS_CONFIG_DEBUG
