#if GOS_CONFIG_LVGL_BOOT_LOGO
image:
  - file: 'https://esphome.io/_images/logo.png'
    id: boot_logo
    resize: 200x200
    type: RGB565
#endif // GOS_CONFIG_LVGL_BOOT_LOGO

#define MY_FONT montserrat_18

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: lvgl_display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

lvgl:
  log_level: INFO
#if 0
  displays:
    - display_id: gosBsp_display
#endif
  buffer_size: 50%
  touchscreens:
    - touchscreen_id: gosBsp_touchscreen
  default_font: MY_FONT
  disp_bg_color: 0x000000
  update_interval: 2s
#if GOS_CONFIG_LVGL_IDLE
  on_idle:
    timeout: !lambda "return (id(lvgl_display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
#ifdef GOS_BSP_HAS_backlight
      - light.turn_off: gosBsp_light_binary_backlight
#endif
      - lvgl.pause:
#endif

#include "ui/lvglTheme.yaml"

#include "ui/lvglNavigation.yaml"
#if GOS_CONFIG_LVGL_BOOT_LOGO
#include "ui/lvglBootLogo.yaml"
#endif

  pages:
#include "ui/page1.yaml"
#include "ui/page2.yaml"
#include "ui/page3.yaml"
#include "ui/page4.yaml"

// Next are the page extras that are not part of the lvgl: definition

#include "ui/page1add.yaml"
#include "ui/page2add.yaml"
#include "ui/page3add.yaml"
#include "ui/page4add.yaml"

#ifdef GOS_BSP_HAS_backlight
esphome:
  on_boot:
  - priority: 50
    then:
      - light.turn_on: gosBsp_light_binary_backlight
#endif // GOS_BSP_HAS_backlight

#if GOS_CONFIG_LVGL_BOOT_LOGO
esphome:
  on_boot:
  - priority: 50
    then:
      - delay: 5s
      - lvgl.widget.hide: boot_screen
#endif // GOS_CONFIG_LVGL_BOOT_LOGO

#if GOS_CONFIG_LVGL_IDLE && GOS_CONFIG_LVGL_ANTIBURN
switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:
#endif // GOS_CONFIG_LVGL_IDLE && GOS_CONFIG_LVGL_ANTIBURN

