#ifdef GOS_BSP_HAS_sensor_internal_temperature
sensor:
  - platform: internal_temperature
    name: "System Temperature"
    update_interval: 5s
    #if GOS_CONFIG_LVGL
// xxx move to lvgl code
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]
    #endif // GOS_CONFIG_LVGL
#endif // GOS_BSP_HAS_sensor_internal_temperature
