#ifdef GOS_BSP_HAS_sensor_internal_temperature

#if 0	// xxx in lvgl for now until yaml merging is a bit smarter
sensor:
  - platform: internal_temperature
    name: "System Temperature"
    update_interval: 5s
#endif

#endif // GOS_BSP_HAS_sensor_internal_temperature
